### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jimthedev** [KnisterPeter/vscode-commitizen#1]
Hi there,

This looks interesting. I've got it installed. How do I use it? 

Thanks,

Jim

**Comment by KnisterPeter** [comment]
If you open the command pannel with `ctrl+shift+p` (or `command+shift+p`) then type `commit` you see the entry `conventional commit`.
Choose that one and answer the questions afterwards and your commit is done.

This requires that you upfront 'git state' your changed files or just change everything with 'git add .'.
I'm thinking about if nothing is staged, then just stage all, but it could be unexpected.

**Comment by KnisterPeter** [comment]
I'll have to provide some information on the [README](https://github.com/KnisterPeter/vscode-commitizen/blob/master/README.md) I guess. :smile:

**Comment by jimthedev** [comment]
Good idea :) yeah I would not stage for people. It goes against pretty much everything git stand for 😄  Nice work! You should put a PR to list it on the commitizen docs!

**Comment by jimthedev** [comment]
Ps. We need this plugin for atom!

**Comment by KnisterPeter** [comment]
I will create a PR.
If you like it we could move it to the commitizen github-org.

Unfortunately I'm not an atom user and not even know their APIs. Someone else has to create it.

**Comment by KnisterPeter** [comment]
Done: commitizen/cz-cli#397

**Comment by KnisterPeter** [comment]
Oh, by the way is there a logo I could integration. It would look a lot nicer. :smile:

**Comment by jimthedev** [comment]
Yeah I'd like to move to the commitizen org if you're open to it and I can give you admin access there. Let me confirm first with @LinusU that that'd be ok. We don't have a logo yet except [this ugly thing](https://pbs.twimg.com/profile_images/655073857733308416/qxl3hPVG.jpg) but we're totally looking for one if someone has a good idea for something.

No worries on the Atom plugin. Your code alone can be a blueprint for someone. Appreciate all your hard work.

**Comment by KnisterPeter** [comment]
Nice. I'd be glad to contribute. I'll love what you started with commitizen.

**Comment by LinusU** [comment]
That sounds awesome 🙌

**Comment by KnisterPeter** [comment]
Great. I'll move over then.

**Comment by KnisterPeter** [comment]
@jimthedev bump
