### ISSUE TITLE
Feature request: support additional cz-customizable configurations

### ISSUE THREAD

**Issue by wmgregory** [KnisterPeter/vscode-commitizen#165]
Currently it's mentioned right now it the readme that there is an integration with the readme, but it only seems to be a limited integration, heres a few configurations I'd like to see:

```TypeScript
  allowTicketNumber: boolean;
  isTicketNumberRequired: boolean;
  ticketNumberPrefix: string;
  skipQuestions: string[],
```

eg. `feat(Scope): ITM-291 subject about feature `

Ticket Number is the Footer but instead of being at the end, it's at the beginning of the subject.

**Comment by KnisterPeter** [comment]
Good idea. Every PR is welcome.
