### ISSUE TITLE
Is vscode-commitizen support emoji?

### ISSUE THREAD

**Issue by wizardnet972** [KnisterPeter/vscode-commitizen#173]
Did `vscode-commitizen` support  [streamich/git-cz adapter](https://github.com/streamich/git-cz)?

from [cz-cli](https://github.com/commitizen/cz-cli) repo:
> If you're not working in a Commitizen friendly repository, then git cz will work just the same as git commit but npx git-cz will use the streamich/git-cz adapter.

**Comment by KnisterPeter** [comment]
@wizardnet972  I don't get the point of your request. Can you please explain a bit more?

Regarding the title and the emojis: vscode should support emojis if the used font supports emojis. Everything else is depending on git. So this extension does not need to specifically support emojis.
