### ISSUE TITLE
Command failed with exit code 1 (EPERM): git commit -m feat(scope): Description

### ISSUE THREAD

**Issue by dawidjaniga** [KnisterPeter/vscode-commitizen#213]
Hello there,
When I commit changes via vscode-commitizen I'm getting the error:
`Command failed with exit code 1 (EPERM): git commit -m feat(archive): Init`
![Screenshot 2019-08-27 at 08 52 24](https://user-images.githubusercontent.com/8960952/63748023-ce236d80-c8a8-11e9-96e9-ed6c11a033c5.png)

Steps to reproduce:

1. CMD+Shift+P
2. Select `Commitizen: conventional commit`
3. Select `feat`
4. Type only required information - description of change

**Comment by dawidjaniga** [comment]
I guess when the problem is: changes were not add to stage. It's working as intended now.
What do you think about adding details to the error?

**Comment by KnisterPeter** [comment]
I think it would help to check if there are staged files

**Comment by j78742** [comment]
Hi,
I got an error when I try to commit my changes.

**Comment by bm-stschneider** [comment]
Having a multiroot workspace seems to add some problems with the commitizen support.
In one of the roots it works and in the other it does not?!
The files get staged according to vscode. I can copy paste the git command into a terminal and it works as well.

```
Commitizen support started
About to commit '<message>'
Staging all files (enableSmartCommit enabled with nothing staged)
Command failed with exit code 1 (EPERM): git commit -m <message>
Error: Command failed with exit code 1 (EPERM): git commit -m <message>
	at makeError (~/.vscode-insiders/extensions/knisterpeter.vscode-commitizen-0.8.3/node_modules/execa/lib/error.js:58:11)
	at handlePromise (~/.vscode-insiders/extensions/knisterpeter.vscode-commitizen-0.8.3/node_modules/execa/index.js:335:18)
```

**Comment by KnisterPeter** [comment]
I think right now the cwd in which the command is executed is the first project it the workspace. That will then result in wrong behaviour.

**Comment by bm-stschneider** [comment]
So how does the extension decide where to run? since I selected the repository during the input process?

**Comment by dawidjaniga** [comment]
What do you think about choosing to which repo should extension commit?

**Comment by KnisterPeter** [comment]
@bm-stschneider The moment I've added support for workspaces it was not possible to get which repository is selected. That may have changed, I'm not sure. I by myself does not use vscode with workspaces.

**Comment by KnisterPeter** [comment]
Anyone wants to create a PR?

**Comment by tehshane** [comment]
I'm not able to work on a PR at the moment, but there's documentation on multi-root workspaces that might help. Specifically, the `showWorkspaceFolderPick` method.

https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs

**Comment by bm-stschneider** [comment]
or this https://github.com/microsoft/vscode-extension-samples/blob/master/basic-multi-root-sample/src/extension.ts

**Comment by Lucs1590** [comment]
I had the same problem!
:cry:

**Comment by Haven09** [comment]
I had the same problem too, and how can i get additional information

**Comment by sehwol** [comment]
> 
> 
> I had the same problem too, and how can i get additional information

![foo](https://user-images.githubusercontent.com/50994416/87246815-d6ad7400-c479-11ea-9688-c10f6f4a061b.PNG)

For those that still get this error, try updating/reinstalling the latest version of the extension. If that doesn't work, there's now an option to double quote the message that gets passed to git (see screenshot). Try ticking that and trying again, see if that works.
