### ISSUE TITLE
Command failed with exit code 128 ( Unkown system error)

### ISSUE THREAD

**Issue by j78742** [KnisterPeter/vscode-commitizen#215]
Hi, 
When I try to commit the changes, I'm getting the error as follows:
![image](https://user-images.githubusercontent.com/16643891/64220697-e4f73f00-cefc-11e9-92c2-2c465cbf7601.png)

And I found that everthing is okay when I open the project from the root directory. 

Error occurs whenever I open the project from the parent folder.

Maybe, this error is related to  the directory depth (not the directoy where the .git file exists )?

**Comment by KnisterPeter** [comment]
Thanks for reporting

**Comment by KrishnaPG** [comment]
Facing the same problem. Putting quotes around the message string seems to work-around it. This happens on Windows 10

**Comment by KnisterPeter** [comment]
Ideally the extensions should put quotes around it
