### ISSUE TITLE
Prompt does not skip questions defined in .cz-config.js

### ISSUE THREAD

**Issue by yassinecc** [KnisterPeter/vscode-commitizen#216]
First off thanks for the extension, it has become an essential for me!

I have a `.cz-config.js` file with the following fields:

```
module.exports = {
  types: [
    { value: "feat", name: "feat:       A new feature" },
    { value: "fix", name: "fix:        A bug fix" },
    // Some other types
  ],
  messages: {
    type: "Select the type of change that you're committing:",
    scope: "\nDenote the SCOPE of this change (optional):",
    subject: "Write a SHORT, IMPERATIVE tense description of the change:\n",
    body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    confirmCommit: "Are you sure you want to proceed with the commit above?"
  },
  skipQuestions: ["footer", "breaking"] // HERE
};
```

I am using cz-customizable as such in `package.json`:

```
"scripts": {
   "commit": "git-cz",
// some other scripts
},
"config": {
    "commitizen": {
      "path": "node_modules/cz-customizable"
    }
  }
```

With this configuration, `git cz` effectively skips the footer and breaking changes prompts, but running conventional commit from the command panel still asks me those questions.

Is skipping questions supposed to work on this extension or is my config wrong?
Thanks!

**Comment by KnisterPeter** [comment]
That would be a nice feature. Maybe you want to implement it?

**Comment by yassinecc** [comment]
Hello @KnisterPeter I have opened a PR, let me know what you think
