### ISSUE TITLE
Cannot read property 'czConfig' of undefined

### ISSUE THREAD

**Issue by jiayisheji** [KnisterPeter/vscode-commitizen#222]
I select type, next vscode error

```text
Cannot read property 'czConfig' of undefined
```

vs code

```text
version: 1.39.1 (system setup)
commit: 88f15d17dca836346e787762685a40bb5cce75a8
date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
vscode-commitizen: v0.8.4
```

> I roll back to `v0.8.3` working properly

**Comment by yusiwen** [comment]
I'm having this issue too. Where is 'czConfig'?

**Comment by jiayisheji** [comment]
@yusiwen I don't know, you also switch to the previous version, may be version conflict bug.

**Comment by KnisterPeter** [comment]
Is there a stacktrace or other extra information? I'm struggeling to debug this.

**Comment by jiayisheji** [comment]
@KnisterPeter I'm sorry, vscode did not prompt other information.

**Comment by bboehm86** [comment]
I got the same issue. This seems to be the result of this [commit](https://github.com/KnisterPeter/vscode-commitizen/commit/6ab8fd9eaba6da0457e9f4059ac6cdac09ac4e62). Might be an issue with the transpiler output for the async functions...

**Comment by princeblade** [comment]
> Is there a stacktrace or other extra information? I'm struggeling to debug this.

I got the same issue. use the example ".cz-config.js"  config file from  cz-customizable

**Comment by jiayisheji** [comment]
@princeblade You roll back v0.8.3 and wait for the author to fix it before upgrading

**Comment by andfk** [comment]
I think i've found the issue (hopefully) but somehow the config brakes once you add `allowCustomScopes` prop to `.cz-config.js`.

If you comment this prop from default config (https://github.com/leonardoanalista/cz-customizable/blob/master/cz-config-EXAMPLE.js) it works, at least on my end. I hope this helps!

**Comment by nerdmax** [comment]
+1
@andfk Thank you for posting your solution but unfortunately, it doesn't work for me. 😭

**Comment by mloetkemann** [comment]
I got same issue when I set `allowCustomScopes=true` in .cz-config.js

**Comment by dschox** [comment]
Any news on this?

**Comment by gaelhameon** [comment]
I had the same issue and @andfk 's solution worked for me! @nerdmax , make sure you quit vscode and reopen it, it l didn't think of doing that at first so I thought it wasn't working ...

**Comment by jiayisheji** [comment]
@gaelhameon  roll back to v0.8.3 ok

**Comment by jiayisheji** [comment]
version: 1.47.2 (user setup)
commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

v0.9.2 

error

```text
Cannot read property 'czConfig' of undefined
```

**Comment by jiayisheji** [comment]
@KnisterPeter I found that using custom `scopes` will appear `Cannot read property'czConfig' of undefined`

**Comment by KnisterPeter** [comment]
@jiayisheji Did you PR fixed this issue? I could create a release if you need that.

**Comment by jiayisheji** [comment]
@KnisterPeter ok
