### ISSUE TITLE
Use commitizen/conventional-commit-types

### ISSUE THREAD

**Issue by qkdreyer** [KnisterPeter/vscode-commitizen#271]
Hello,

It would be great if this extension could use the same default types than the ones used by [commitizen/cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) for [commitizen/cz-cli](https://github.com/commitizen/cz-cli).

Reference : [commitizen/conventional-commit-types](https://github.com/commitizen/conventional-commit-types/blob/master/index.json)

https://github.com/KnisterPeter/vscode-commitizen/blob/61f6b887d3f1b183700599a916091e1958398b45/src/extension.ts#L141-L182

**Comment by leepatrick-canoo** [comment]
This appears to still be an issue for me; specifically the mismatch between `feature` and `feat`. The plugin is not compatible with the Conventional Commits specification as-is: https://www.conventionalcommits.org/en/v1.0.0/#specification
