### ISSUE TITLE
Only the first line makes it to the final commit message

### ISSUE THREAD

**Issue by zbream** [KnisterPeter/vscode-commitizen#325]
My commits are only saving the first line of the final message; the body is missing.

I don't have any extension configuration set in this repo/environment.

---

Fails in `0.9.3`:

![093-log](https://user-images.githubusercontent.com/16364440/89830460-34d97f80-db2a-11ea-85c0-aa4406d642c3.PNG)

![093-message](https://user-images.githubusercontent.com/16364440/89830471-399e3380-db2a-11ea-9102-8a84773a3a5f.PNG)

---

Works in `0.8.4`:

![084-log](https://user-images.githubusercontent.com/16364440/89830518-4de23080-db2a-11ea-913a-e4bfd3f29b35.PNG)

![084-message](https://user-images.githubusercontent.com/16364440/89830527-5175b780-db2a-11ea-9c7e-606f39e8a477.PNG)

---

VSCode Version:

```
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by cgatian** [comment]
Also experiencing this issue. My footer is completely cut off.

**Comment by cgatian** [comment]
If `execa` is configured with `shell` is set to `false`, and `quoteMessageInGitCommit` is `false` the command works properly.

```
Version: 1.48.2 (system setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by zbream** [comment]
It looks like d275e4c introduced this, which is causing commits to fail in Windows. 

As @cgatian mentioned, [`shell: true`](https://github.com/sindresorhus/execa#shell) will use **cmd.exe**, and apparently it's [fairly difficult](https://stackoverflow.com/questions/5064563/add-line-break-to-git-commit-m-from-the-command-line) to find a cross-platform way of passing linebreaks to `git commit-m`.

**Comment by cgatian** [comment]
Still an issue. Makes plugin unusable

**Comment by cgatian** [comment]
It's still a problem

**Comment by yi-Xu-0100** [comment]
I encountered the same problem in v0.10.2 (windows), is there a solution now?

**Comment by cgatian** [comment]
No

**Comment by yi-Xu-0100** [comment]
@cgatian Based on your discussion above, I tested the new extension. As you said, the repair can be completed. In order to be consistent with the original state, I made this setting option as part of the configuration and submitted a PR, looking forward to the author's review and merging! @KnisterPeter

**Comment by KnisterPeter** [comment]
I'll merge it today and create a release

**Comment by cgatian** [comment]
Oh thank God

**Comment by KnisterPeter** [comment]
Thanks @yi-Xu-0100 🙂
