### ISSUE TITLE
Cannot use scopeOverrides and scopes at the same time

### ISSUE THREAD

**Issue by carvinlo** [KnisterPeter/vscode-commitizen#358]
Hi, for me this is a very useful plugin, but in use I found some problems:
1. cannot use `allowCustomScopes` option and `scopes` option at the same time, otherwise it will cause an error: `Cannot read property 'czConfig' of undefined`.
2. `scopeOverrides` option does not work.
Thanks!

> `vscode-commitizen`'s version: 0.9.3

**Comment by KnisterPeter** [comment]
@carvinlo Thanks for reporting. Any help is appreciated.
