### ISSUE TITLE
Consider the allowBreakingChanges parameter in the configuration

### ISSUE THREAD

**Issue by ProMastersss** [KnisterPeter/vscode-commitizen#402]
The extension does not take into account the allowBreakingChanges configuration parameter. I would like it to be taken into account by the extension

**Comment by ProMastersss** [comment]
Sent a pull request #404

**Comment by KnisterPeter** [comment]
Merged with #406

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
Will be shipped with 0.10.0

**Comment by KnisterPeter** [comment]
Will be shipped with 0.10.0
