### ISSUE TITLE
Can commit msg subject length be increased?

### ISSUE THREAD

**Issue by chhschou** [KnisterPeter/vscode-commitizen#41]
We've a couple of things to put into the subject line and the extension locking it down to 50 character limit is too short for us. Can this be tweaked?

**Comment by cgatian** [comment]
Whats limiting you to putting this information in the additional into the long description?

**Comment by chhschou** [comment]
My format looks like "STY1234 - <subject>" so I lose 10 characters before actual subject even begin. I want my subject to be descriptive, not forced to make it generic and require the long description to comprehend. You will find the subject often exceeds 50 characters in other projects such as the Angular project. 

When I use commitizen on command line I don't get hit by this limit. I actually use validate-commit-msg to set `"maxSubjectLength": 100,` to limit the subject to 100 characters and it works well for me on the command line, although I think 80 could have also worked.  

What is the reasoning behind choosing 50 characters as the subject length limit? Is there a standard published somewhere that calls for the 50 character limit?

It is a great extension, but I'm finding I am reaching for the terminal from time to time and it is introducing some friction. 50 is just too tight for me.

**Comment by cgatian** [comment]
First let me just say Im not a maintainer of this repository.  I'm sorry if I mislead you. I really just wanted to hear your use case. Thank you for providing it.

**Comment by KnisterPeter** [comment]
I could make it optionally configurable. Sure.
