### ISSUE TITLE
Breaking changes missing.

### ISSUE THREAD

**Issue by SkeLLLa** [KnisterPeter/vscode-commitizen#411]
After merging https://github.com/KnisterPeter/vscode-commitizen/pull/406 breaking changes no longer available. And there's no documentation about how to configure it. Also this option is not available in extension config.

**Comment by KnisterPeter** [comment]
@SkeLLLa  Thanks for reporting. A PR is very welcome.

**Comment by SkeLLLa** [comment]
@KnisterPeter I could try, but I don't get the idea that was implemented in PR https://github.com/KnisterPeter/vscode-commitizen/pull/406 that cause this bug. 

And I rather label it not as "enchantment", but as "regression".

**Comment by ProMastersss** [comment]
@SkeLLLa I seem to see a problem. In the near future, I will correct in my corrections and make a PR

**Comment by KnisterPeter** [comment]
Changed the label to bug.

**Comment by ProMastersss** [comment]
Made a fix ##413

**Comment by KnisterPeter** [comment]
The release is on the way as `0.10.2`
