### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by cgatian** [KnisterPeter/vscode-commitizen#42]
If husky is added into the pipeline to lint on precommit, you may encounter linting errors.  Current the only way to see them is if you hover over the error message.  Is there a better way in VS code to display these messages to the developer?

![image](https://user-images.githubusercontent.com/1752170/30961745-4d9281a6-a415-11e7-8f44-96bc3270cd4e.png)

**Comment by cgatian** [comment]
@KnisterPeter If you have any ideas in mind, I can take a look into it. Perhaps saying, "Commit failed" and append the error message?

**Comment by KnisterPeter** [comment]
I'll think about it. Thanks for reporting.

**Comment by KnisterPeter** [comment]
Currently I use [execa](https://github.com/sindresorhus/execa) to run git in a forked process. This returns the stdout of the process.

It maybe be possible to output the stdout result in a vscode.OutputPanel and open it.
This should be configurable like the task output.
