### ISSUE TITLE
High CPU usage, unable to type

### ISSUE THREAD

**Issue by chhschou** [KnisterPeter/vscode-commitizen#44]
ubuntu: 16.04
vscode: 1.16.1
vscode-commitizen: 0.4

I would sometime get a high CPU usage immediately after starting vscode. I don't think it is project dependent, but the project that I get this on has working changes.
The process chewing up CPU and keeps me warm is 
![image](https://user-images.githubusercontent.com/429067/31207617-e655fe92-a9db-11e7-82ea-97941a7daa2f.png)

I haven't found a workaround yet. Disable vscode-commitizen extension and terminate the CPU hogging process will get me back on. I noticed when the lockup happens the source control icon is 
![image](https://user-images.githubusercontent.com/429067/31207696-5cc95bd2-a9dc-11e7-8450-6789d2eb35e1.png) and it never recovers.

**Comment by KnisterPeter** [comment]
I'll try to investigate this. Never seen this before.

**Comment by chhschou** [comment]
Thanks please let me know if you need more information.
