### ISSUE TITLE
Why didn't I fill in the body and footer parts？

### ISSUE THREAD

**Issue by HaiRongHaHA** [KnisterPeter/vscode-commitizen#443]
Hello, I filled in body and footer (breaking changes & issue)_ But in fact, my commit information only contains the header part. Do you not support filling in the body and footer parts?

**Comment by KnisterPeter** [comment]
@HaiRongHaHA That would be a bug.

**Comment by HaiRongHaHA** [comment]
> @HaiRongHaHA That would be a bug.

Please have time to repair it. I still want to use this tool. If you repair it, please reply to me. Thank you very much！

**Comment by KnisterPeter** [comment]
Hi @HaiRongHaHA, I don't use this extension currently that often.
Please provide a PR, I'm happy to merge it then.

**Comment by LongYue9608** [comment]
```
npm install -g commitizen cz-conventional-changelog
echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc
```
You can directly use git cz to replace git commit.
@HaiRongHaHA

**Comment by HaiRongHaHA** [comment]
@LongYue9608 你是中国人吧，我就写中文了，谢谢你的回答，git cz这个我知道，我就是想用这个插件，所以提这个issue想让作者改，哈哈哈，谢谢你哦！

**Comment by HaiRongHaHA** [comment]
@KnisterPeter ok！I will😏  thank you！！！By the way, why don't you use this extension? You're the author！

**Comment by KnisterPeter** [comment]
I used it a lot when I've created it.
Now I write the commit messages manually again. Not sure why
