### ISSUE TITLE
add - A command or add . Command used inside plug-in?

### ISSUE THREAD

**Issue by LongYue9608** [KnisterPeter/vscode-commitizen#444]

**Comment by KnisterPeter** [comment]
@LongYue9608 I don't understand this question. Please be a bit more specific and add more details to your request

**Comment by LongYue9608** [comment]
1. git add .  or git add -A
2. git commit -m'xxxx'
3. git push 
The plug-in helped us to do the first step and the first step，I want to know which command is the first step in the plug-in。
git add .  or git add -A
@KnisterPeter

**Comment by KnisterPeter** [comment]
@LongYue9608 Neither nor. This extension just runs `git commit` when you call it's commitizen command.
You need to add and prepare your git stage on your own. vscode is already quite good at that.

**Comment by LongYue9608** [comment]
I'm just confused that when I add a new file and run the plug-in, I can directly commit without git add @KnisterPeter

**Comment by KnisterPeter** [comment]
@LongYue9608  Not sure on your process of adding files and calling this extension.
Just be sure I wasn't wrong, I did a quick search for `add` which isn't called in this extension: https://github.com/KnisterPeter/vscode-commitizen/search?q=add

**Comment by LongYue9608** [comment]
![step](https://user-images.githubusercontent.com/25579482/109154449-42461680-77a9-11eb-8582-569f1b78a884.gif)

Commit is not allowed if there are no files in the temporary storage area. However, when I use the plug-in, I will automatically add to the temporary storage area and commit. I want to know which command is used inside the plug-in,git add . or git add -A?I'm sorry, I just want to know that
@KnisterPeter

**Comment by KnisterPeter** [comment]
Ah, I've found it (long time ago that I've written and used it).
Here you have the function which does it:
https://github.com/KnisterPeter/vscode-commitizen/blob/8af48b51d705506b470a752dcd5d02ec4808b233/src/extension.ts#L309-L328

It is the `git.stageAll` command provided by vscode. If you disable 'enableSmartCommit' this will not happen.

**Comment by KnisterPeter** [comment]
@LongYue9608 Did that help you?
