### ISSUE TITLE
Support selecting scopes even if custom scopes allowed

### ISSUE THREAD

**Issue by goodmind** [KnisterPeter/vscode-commitizen#47]
I defined scopes in config, but also allowed custom scopes. I can't select defined scopes then. Is this supposed to be like this?

**Comment by KnisterPeter** [comment]
Sounds like a bug

**Comment by bm-stschneider** [comment]
yep got the same issue here.

**Comment by KnisterPeter** [comment]
I think the current issue is that there is no UI element in vscode which allows predefined values as well as custom ones.
One solution would be to create the predefined list and add an entry 'custom' which then - if selected - opens a simple input dialog.

**Comment by bm-stschneider** [comment]
Would it be possible to read the path for the config from the package json and use the there defined config.js to get the predefined custom elements in a list just like with the type=?

**Comment by KnisterPeter** [comment]
Sure.

**Comment by skyquartam** [comment]
> I think the current issue is that there is no UI element in vscode which allows predefined values as well as custom ones.
> One solution would be to create the predefined list and add an entry 'custom' which then - if selected - opens a simple input dialog.

Hi, any plan on implementing this?

**Comment by KnisterPeter** [comment]
If you like you can make a PR. Every help is welcome. :smiley:

**Comment by KnisterPeter** [comment]
Released as v0.8.1 :rocket:
