### ISSUE TITLE
Support Multi folders

### ISSUE THREAD

**Issue by ProMastersss** [KnisterPeter/vscode-commitizen#475]
There is a problem if several project folders with their own repositories are added to the workspace. You need to correct line 82 of the extension.ts file, where the first folder is always selected. I haven't found how to do it elegantly yet. Maybe there will be suggestions? I haven't found a way to automatically detect the current repository or active folder

**Comment by KnisterPeter** [comment]
Hi @ProMastersss, it's not easy to do and would require a bigger rewrite. Therefore I didn't implemented that for now. Feel free to send a PR.

**Comment by ProMastersss** [comment]
@KnisterPeter #476 Added support. See if this option is suitable?

**Comment by KnisterPeter** [comment]
Merged with #476

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
@ProMastersss released as 0.13.1
