### ISSUE TITLE
Feature request: Support additional prompts defined by commitizen adapters

### ISSUE THREAD

**Issue by chrisdevereux** [KnisterPeter/vscode-commitizen#5]
Some custom commitizen configs define additional prompts (eg. https://github.com/atlassian/cz-lerna-changelog needs to know which packages in a monorepo to count a change as affecting).

Would be nice if vscode-commitizen could support these too. Maybe instead of hardcoding the series prompts, it could defer to the installed commitizen adaptor (perhaps by passing in a custom io interface in place of commitizen's inquirer.js instance?).

**Comment by KnisterPeter** [comment]
Nice idea

**Comment by chrisdevereux** [comment]
Downside would be that a commitizen adaptor might try to read from stdin directly, which we couldn't intercept.

**Comment by KnisterPeter** [comment]
Overwriting `process.stdin` isn't a nice idea :scream:

**Comment by yetithefoot** [comment]
I'm using `cz-customizable` adapter that describes less strict rules.
`cz-customizable` prompt relies on `questions.js` file that specifies `inquirer` questions pipeline. Is it poissible that extension also relies on that spec?

**Comment by KnisterPeter** [comment]
@yetithefoot I don't think that its a good idea to rely on a format which is inquirer dependent. That ties this format into this dependency. But you are right with the idea that the workflow in this extension should be configurable or extensible.
