### ISSUE TITLE
Using it as SCM provider

### ISSUE THREAD

**Issue by Igmat** [KnisterPeter/vscode-commitizen#50]
I'm not sure that it's possible, but it could be great if we could use `commitizen` inside source control tab in VS Code instead of using additional command from palette. Have you thought about it, are there any caveats that prevents such feature?

**Comment by KnisterPeter** [comment]
From first perspective this is a nice idea. But it is a lot work and probably too much.
A SCM provider must implement all interfaces required for vscode to show diffs, changes and stages (related to git).
If using with some other SCM it would be even more work. And commitizen is not tied to git but only to commit messages.
