### ISSUE TITLE
Error command 'vscode-commitizen.commit' not found

### ISSUE THREAD

**Issue by phaneendra** [KnisterPeter/vscode-commitizen#52]
Have commitzen installed locally as an yarn/npm package.

I get this "error : command 'vscode-commitizen.commit' not found" when ever trigger the command.
Running VS code - Version 1.19.2 (1.19.2).

not sure what is wrong or causing this issue.

**Comment by KnisterPeter** [comment]
Thats strange. `vscode-commitizen.commit`  is the activation command for this extension.
When executing it, the extension should be started.
Can you reinstall the extension and restart vscode afterwards, then try again?

**Comment by phaneendra** [comment]
thought this extention works with cz-customizable 
package.json as the below entries in devDependencies
```
"commitizen": "^2.9.6", 
"cz-customizable": "^5.2.0",
```

with a file `.cz-config.js` placed in the workspace, it throws the error `error : command 'vscode-commitizen.commit`

without the file it works

**Comment by phaneendra** [comment]
https://github.com/phaneendra/dev-starter/blob/master/.cz-config.js[](url)

**Comment by KnisterPeter** [comment]
There must be a problem parsing that file. I'll have a look.

Phaneendra <notifications@github.com> schrieb am So., 28. Jan. 2018, 23:01:

**Comment by phaneendra** [comment]
update on the reason for the error, the developer console shows the below issue 
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'lerna/lib/Repository'
    at Function.Module._resolveFilename (module.js:470:15)
```
was using `cz-config.js` to load all lerna packages into custom scopes, by importing `@commitlint/config-lerna-scopes` which depends on `lerna/lib/Repository` 

But am not sure why vscode fails to load the module though its installed in the workspace node_modules.

**Comment by KnisterPeter** [comment]
Good catch. The extension does not resolve modules in the project folder. That is causing this issue.

**Comment by anishmittal2020** [comment]
Please resolve this.

**Comment by Iar0** [comment]
Same error here, I don't have any `cz-config.js` setup but I get the error anyway

**Comment by bm-stschneider** [comment]
Maybe the api has changed now as well.
![image](https://user-images.githubusercontent.com/30625381/66983285-7fc86900-f0b8-11e9-8893-ddb4350f9b9e.png)
