### ISSUE TITLE
Command failed with exit code 128

### ISSUE THREAD

**Issue by conye9980** [KnisterPeter/vscode-commitizen#520]
![image](https://user-images.githubusercontent.com/3719375/122240139-714bd980-ceb9-11eb-86f7-21de119a8e59.png)

When trying to commit with Commitizen I get the above error. There is  a fixed issue in the Issues here that says to put quotes around the commit message and it works but no luck for myself.

Any ideas?

**Comment by ALABSTM** [comment]
Hi @conye9980,

Have you first **initialized your folder** to be tracked by Git? Once done, your _simple_ folder becomes a repository. See the screenshot below. You should click on the "Initialize Repository" button. Then you are good to go and make your commit.

With regards,

![image](https://user-images.githubusercontent.com/46019491/123245058-61954c00-d4dc-11eb-9fc8-c9562f1c8f32.png)

**Comment by conye9980** [comment]
Hi, yeah it's initialized fine. It actually had been working for months and then simply stopped working, I must've made a change somewhere, but disabling/uninstalling & enabling/reinstalling hasn't worked with it.

**Comment by KnisterPeter** [comment]
Hi @conye9980 ,
thanks for reporting. A PR is very welcome to fix this.
