### ISSUE TITLE
Veryfing commits

### ISSUE THREAD

**Issue by euberdeveloper** [KnisterPeter/vscode-commitizen#546]
When I use commitizen from `npm` (I mean a script in `package.json`), I usually add `-S` to sign commits. How to add it when I use this VSCode extension?

**Comment by KnisterPeter** [comment]
Hi @euberdeveloper, I think thats not possible. But a good idea.
Feel free to create a pull request with that feature.

**Comment by euberdeveloper** [comment]
I have no idea of how vscode extensions work, so I have no idea of what am I saying.

Is it possible that the -S flag could be added here (with an option)? https://github.com/KnisterPeter/vscode-commitizen/blob/ba272e258dc6dc99ba2571460261504490ed52ac/src/extension.ts#L298

W

**Comment by KnisterPeter** [comment]
@euberdeveloper  Sure, that would be a good way to add that feature. This extension uses the git cli and you already found the right spot :smiley:
