### ISSUE TITLE
Support commit from a workspace

### ISSUE THREAD

**Issue by lnmunhoz** [KnisterPeter/vscode-commitizen#55]
I usually work in a vscode workspace and there's always multiple repository folders that I am navigating. If you try to commit from a workspace, it will give you an error:

![screenshot 2018-03-17 20 14 44](https://user-images.githubusercontent.com/4376835/37555790-db8a02a0-2a1f-11e8-9407-b4b650cb07f0.png)

Logs the devtools:
```
Command failed: git commit -m build(fail): This will fail fatal: Not a git repository (or any of the parent directories): .git
```

If you use the standard commit package from vscode, the first thing it does is to ask for the repository. This might be a good additional feature to add to this project to support working in workspaces.

**Comment by huoshiqiu** [comment]
+1

**Comment by axcosta** [comment]
+1
