### ISSUE TITLE
No auto commit feature

### ISSUE THREAD

**Issue by emindeniz99** [KnisterPeter/vscode-commitizen#572]
Hello, thanks for your extension.
I saw another extension that gives an opportunity to review the commit message. Could you add this feature, and what do you think about this feature. You can review the extension, also I added a demo gif.
![gif](https://github.com/vivaxy/vscode-conventional-commits/blob/master/assets/docs/demo.gif?raw=true)
https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits

**Comment by KnisterPeter** [comment]
@emindeniz99 Interesting idea. I'm open for a PR to add this. I would request to make this review optional and disabled by default. But I would like to merge that if you implement it.

**Comment by emindeniz99** [comment]
Hello @KnisterPeter, I opened the PR https://github.com/KnisterPeter/vscode-commitizen/pull/578, Could you review it?
It only fills the commit message for the first repo at vs code source control window. Vivaxy's conventional commits repo has this feature, we can add this improvement. But, It works for now.

**Comment by KnisterPeter** [comment]
Sure, look at my comments in your pull request.
