### ISSUE TITLE
Multi-repo workspaces get only the first commitizen custom config

### ISSUE THREAD

**Issue by jwulf** [KnisterPeter/vscode-commitizen#60]
At the moment, when I open three git repos in a workspace, the extension reads the `.cz-config.js` file from the first repo and offers its custom scopes for commits to _all_ repos in the workspace.

If I reorder the repos in the workspace root and reload the window, then the new first repo's customisation is read.

What I would like is that the customisation that corresponds to the currently selected Source Control Provider is used when committing in that repo. 

Can you get the "currently selected repository" as a context?

**Comment by BrighTide** [comment]
👍

**Comment by KnisterPeter** [comment]
Yep right. This is a limitation right now. It should be extended do handle workspaces well.
