### ISSUE TITLE
Feature request: accept custom footerPrefix in cz-config

### ISSUE THREAD

**Issue by sjakos** [KnisterPeter/vscode-commitizen#62]
cz-customizable allows for the customization of the footer prefix, changing it from the default 'Closes' to any user-defined string in cz-config.js

It would be great if the same configuration could be supported through this extension.

**Comment by KnisterPeter** [comment]
@sjakos Nice idea. PRs are welcome.

**Comment by KnisterPeter** [comment]
Released in v0.8.0 :rocket:
