### ISSUE TITLE
[BUG] can't skip questions

### ISSUE THREAD

**Issue by TomerEternal** [KnisterPeter/vscode-commitizen#672]
when i add for example "scope" to the skipQuestions the question remains

**Comment by KnisterPeter** [comment]
Hi @TomerEternal , thanks for reporting. A PR to fix this is very welcome.

**Comment by TibebeJS** [comment]
@KnisterPeter I've created a PR for that. please take a look

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
Released in v1.0.3
