### ISSUE TITLE
commit not working with windows git bash as terminal

### ISSUE THREAD

**Issue by Kallows** [KnisterPeter/vscode-commitizen#702]
Hi @KnisterPeter 

trying to commit I'm getting `exit code 128 fatal: not a git repository...` 
![image](https://user-images.githubusercontent.com/60037912/152828771-14fdc18b-ee33-4dcb-9e4f-1ab7d477a077.png)
according to setting it seems to me that that vsode-commitizen is only working with /bin/sh on UNIX or cmd.exe on Windows. Is there any chance to say the vsocde-commitizen extention to use windows git-bash instead of /bin/sh or cmd.exe? If I changing the shell for VS Windows-Terminal from cmd.exe as well to git-bash it doesn't solve the issue. 

Thank you in advance.

BR,
Kalle

**Comment by KnisterPeter** [comment]
Hi @Kallows, unfortunately I don't have any access to windows so I cannot test this on my side.
There is support for setting a shell:
https://github.com/KnisterPeter/vscode-commitizen/blob/100b7a37e1f5a8ca2406af882bd376b85a020154/package.json#L58-L62

If that doesn't help I'm not sure. The exit code 128 could be anything.

**Comment by KnisterPeter** [comment]
Hi @Kallows, as I've told you I have no windows machine. I cannot test and debug your problem.
We use [execa](https://github.com/sindresorhus/execa) to execute our commands.
Maybe you can play around with it as well to see if the problem is really depending on your shell.
