### ISSUE TITLE
Use SVG icon for command

### ISSUE THREAD

**Issue by rozpuszczalny** [KnisterPeter/vscode-commitizen#703]
The existing icon is unreadable in the UI, so it's hard to say what's that icon for. Since SVG logo of commitizen exists (see https://github.com/commitizen/cz-cli/pull/878, https://github.com/vscode-icons/vscode-icons/pull/2869), it could be used in this project as well.

If you want, I can create a pull request for that.

**Comment by KnisterPeter** [comment]
Hi @rozpuszczalny, a PR is very welcome.
