### ISSUE TITLE
Commits fail on Windows when repository is on a UNC path

### ISSUE THREAD

**Issue by philnagel** [KnisterPeter/vscode-commitizen#734]
On Windows, when trying to commit with this extension, and the repository is located on a UNC path, the commit fails with the following error:

`Command failed with exit code 128: git commit -m "fix(scope): message" '\\some\UNC\path' CMD.EXE was started with the above path as the current directory. UNC paths are not supported. Defaulting to Windows directory. fatal: not a git repository (or any of the parent directories): .git`

I'm not sure if this requires a workaround within CMD.exe, or if the issue is  that commitizen is not using the default command interpreter (in my case, Git Bash). Using the regular, built-in Git functionality from VS Code works fine on this repo.

VS Code Version: 1.64.2
vscode-commitizen version: 1.1.0

**Comment by KnisterPeter** [comment]
@philnagel Thanks for reporting. Since I'm not using windows I cannot work on this, but a PR would be very welcome.
