### ISSUE TITLE
[Feature request] don't autosync when there are unstaged files

### ISSUE THREAD

**Issue by Igmat** [KnisterPeter/vscode-commitizen#76]
I love `autoSync` feature provided by #40.
But I realized that it doesn't fully matches my flow:
1. Make a lot of changes (e.g. 10-20 files)
2. Stage some of them (e.g. 2-3)
3. Commit stages
4. Repeat steps 2 and 3 while there are dirty files
5. Push all commit once

As profit, trigger CI only once for all changes instead of subset.
Probably, it should be opt-in.

**Comment by KnisterPeter** [comment]
Not sure on when to use `autoSync` and when to disable it in your use case.
Right now `autoSync` need to be enabled by a user. When the sync should be done?

**Comment by Igmat** [comment]
I think it could work as follows.
Rework `autoSync` from `boolean` to `enum` that accepts 3 values:
1. `never` - works as current `autoSync: false`
2. `always` - works as current `autoSync: true`
3. `smart` (name could be another)
  a. user staged some files
  b. uses this extension to add commit
  c. extensions checks if there are any unstaged changes in workspace
    - if yes, it does nothings
    - if not, syncs with origin

Is it clear enough?

**Comment by KnisterPeter** [comment]
@Igmat Yes that sounds possible
