### ISSUE TITLE
Feature request: Auto-stage [enableSmartCommit]

### ISSUE THREAD

**Issue by bcanseco** [KnisterPeter/vscode-commitizen#80]
![image](https://user-images.githubusercontent.com/18430599/46319449-b875cd00-c59f-11e8-8315-0ea903367f27.png)

If this setting is on and you have no files staged, the extension should assume you want all files staged and stage them for you. I'm assuming it would be `git add -A -- .`

New to TypeScript, but I'd be happy to submit a PR if you think this is a good idea. I'm thinking we'd need to read from the config and execute the additional command if nothing is staged before line 184.

https://github.com/KnisterPeter/vscode-commitizen/blob/bbddd8151d30adf029dbb118cc2dde25216fab85/src/extension.ts#L181-L184

**Comment by KnisterPeter** [comment]
@bcanseco I think that could be a good addition. Your PR is very much welcome. :smiley:

**Comment by KnisterPeter** [comment]
Released as 0.7.0 :rocket:
