### ISSUE TITLE
How to work with husky prepare-commit-msg

### ISSUE THREAD

**Issue by karlomedallo** [KnisterPeter/vscode-commitizen#886]
Currently we have users that uses cz-cli to commit and in this case, everything works fine since our git commit hook for `prepare-commit-msg` is:
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

exec < /dev/tty && node_modules/.bin/cz --hook || true
```
Now the problem we have is when a user uses your plugin to commit, the commit stalls and nothing happens.

How can I make this work?
Is there a way to detect if the commit is coming from your plugin, so maybe we can disable running the command in the commit hook?

**Comment by inthegreenwild** [comment]
I'm getting a similar issue with an error: 
 .husky/pre-commit: line 8: pnpm: command not found husky - pre-commit hook exited with code 127 (error) husky - command not found in

**Comment by KnisterPeter** [comment]
@karlomedallo Not sure. I don't use commitizen anymore.
