### ISSUE TITLE
Open editor before commit

### ISSUE THREAD

**Issue by ar53n** [KnisterPeter/vscode-commitizen#91]
Hello there is a suggestion to add to the settings so that you can open the editor with a commit for the last check before sending the commit

**Comment by KnisterPeter** [comment]
@ar53n First of all thank for your suggestion. :smiley: 
What should be visible in the editor? Could you explain a bit more of what you are suggesting?
There is the git integration in vscode which allows to show diffs off all changes, isn't this sufficient? What is missing there?

**Comment by ar53n** [comment]
@KnisterPeter Thanks for response. There is a case when I type a large message and make a mistake, I don’t want to type everything again, I want to see the message before making a commit.
Its like a `git config --global core.editor "code --wait"` and after you write `git commit`
<img width="593" alt="2018-10-15 11 03 50" src="https://user-images.githubusercontent.com/7085102/46937455-0394e300-d06a-11e8-8d6a-7e0c8892b555.png">

**Comment by KnisterPeter** [comment]
Oh, you mean the commit message, not the changes.
Right now I'm not happy with the input for commit messages at all. But adding another confirmation step does not seam very usable (or user friendly) to me.

**Comment by virgilwashere** [comment]
I would like to use an editor for the commit message input.

How about utilising a snippet with list selection?
This is from shellman extension.  You can <TAB> through the 3 tabstops, and number 3 prompts with a selection list.
```
	"crypto_hash": {
		"prefix": "crypto hash",
		"body": "${1:hash}=`echo -n \"\\$${2:variableToHash}\" | ${3|md5sum,shasum,sha1sum,sha224sum,sha256sum,sha384sum,sha512sum|} | cut -f1 -d ' '`\n",
		"description": "compute hash of variable (md5, sha, sha1, sha224, sha256, sha384, sha512)"
	},
```

`git-commit` is already a "language" in vscode.
